#!/bin/bash

set -eu

printf "Installing neovim"
curl -OL https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
sudo dpkg -i nvim-linux64.deb
nvim_version=$(nvim --version)
rm nvim-linux64*
printf "Installed neovim ${nvim_version}"

printf "Installing dependancies"
python3 -m pip install pynvi
python3 -m pip install neovim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
sudo apt update
sudo apt install -y ripgrep fzf

curl -OL https://nodejs.org/dist/v18.14.0/node-v18.14.0-linux-x64.tar.xz
tar xvf node-v18.14.0-linux-x64.tar.xz
sudo cp -r node-v18.14.0-linux-x64/bin /usr/
sudo cp -r node-v18.14.0-linux-x64/include /usr/
sudo cp -r node-v18.14.0-linux-x64/lib /usr/
sudo cp -r node-v18.14.0-linux-x64/share /usr/
rm -rf node-v18*
nvim --headless +PackerSync +qa
printf "Instelled dedendancies"

